//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureEngine.LocalizationResx", typeof(LocalizationResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розрахувати.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть університет.
        /// </summary>
        public static string ChooseUniversity {
            get {
                return ResourceManager.GetString("ChooseUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витрати.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Момент, коли ваша заробітня плата рівна платі за навчання.
        /// </summary>
        public static string DotCaption {
            get {
                return ResourceManager.GetString("DotCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вища освіта - це перший та найважливіший крок у твоій майбутній кар&apos;єрі. Ми створили цей веб-сайт, щоб допомогти тобі зробити більш інформований та вдалий вибір вузу та спеціалізації..
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевір, як платять фахівцям різних галузей та як швидко окупиться твоя інвестиція у власну освіту..
        /// </summary>
        public static string GreetingFooter {
            get {
                return ResourceManager.GetString("GreetingFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шановний абітурієнте!.
        /// </summary>
        public static string GreetingHeader {
            get {
                return ResourceManager.GetString("GreetingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень оплати за навчання та рівень зарплати.
        /// </summary>
        public static string PaymentsCaption {
            get {
                return ResourceManager.GetString("PaymentsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плата за навчання.
        /// </summary>
        public static string PaymentsGraphCaption {
            get {
                return ResourceManager.GetString("PaymentsGraphCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіь якість ВНЗ.
        /// </summary>
        public static string PickQuality {
            get {
                return ResourceManager.GetString("PickQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть спеціальність.
        /// </summary>
        public static string PickSpeciality {
            get {
                return ResourceManager.GetString("PickSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибуток.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хороший.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Низкий.
        /// </summary>
        public static string QualityLow {
            get {
                return ResourceManager.GetString("QualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середній.
        /// </summary>
        public static string QualityMiddle {
            get {
                return ResourceManager.GetString("QualityMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумарні витрати i заробіток.
        /// </summary>
        public static string SummaryCaption {
            get {
                return ResourceManager.GetString("SummaryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cумарні витрати.
        /// </summary>
        public static string SummaryCosts {
            get {
                return ResourceManager.GetString("SummaryCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень зарплати.
        /// </summary>
        public static string SummaryGraphCaption {
            get {
                return ResourceManager.GetString("SummaryGraphCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумарний заробіток.
        /// </summary>
        public static string SummarySalary {
            get {
                return ResourceManager.GetString("SummarySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гроші (грн).
        /// </summary>
        public static string xChartAxisCaption {
            get {
                return ResourceManager.GetString("xChartAxisCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час (роки).
        /// </summary>
        public static string yChartAxisCaption {
            get {
                return ResourceManager.GetString("yChartAxisCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть спеціальність.
        /// </summary>
        public static string СhooseSpeciality {
            get {
                return ResourceManager.GetString("СhooseSpeciality", resourceCulture);
            }
        }
    }
}
